[package]
name = "opengl_clockery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
chrono-tz = "0.8.4"
sdl2 = { version = "0.36.0", features = [ "use-pkgconfig", "ttf", "static-link"], default-features = false }
serde_json = "1.0.108"

