[package]
name = "opengl_clockery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bitflags = "2.4.1" ./lol.png
chrono = "0.4.31"
chrono-tz = "0.8.4"
lazy_static = "1.4.0"
once_cell = "1.18.0"
sdl2 = { version = "0.36.0", features = ["use-pkgconfig", "ttf", "bundled", "static-link"], default-features = false }
serde_json = "1.0.108"

